### ISSUE TITLE
BUG: nicht registrierter Consumer fragt nach Liste von Produzenten -> RuntimeException

### ISSUE THREAD

**Issue by naibaf0** [TINF15ITNS/MB#37]
```
Bitte wählen Sie durch Eingabe einer Zahl:
(1) Registrierung beim Server
(2) Liste von Produzenten ansehen
(3) Beenden der CLI
Eingabe: 2
Exception in thread "main" java.lang.RuntimeException: Wrong Payload
    at consumer.Consumer.getProducers(Consumer.java:105)
    at consumer.ConsumerCLI.main(ConsumerCLI.java:53)
```

Hierbei war noch kein Prducer online registriert, falls es damit zu tun hat.
Dieses Szenario funktionierte gestern morgen noch.

**Comment by naibaf0** [comment]
Ich erhalte denselben Bug wenn ich 1 wähle und mich beim Server registrieren will. Dann gescieht dies in ConsumerCLI.java:46 -> Consumer.java:70

**Comment by naibaf0** [comment]
Dies hat mit der Implementierung von instanceof zu tun.

**Comment by naibaf0** [comment]
Fix in 0bcb962c

**Comment by naibaf0** [comment]
Ich befürchte das es denselben Fehler noch an anderen Stellen gibt, dies sollte überprüft werden.

**Comment by naibaf0** [comment]
Dies sollte nun behoben sein. Bitte kontrollieren!
